### ISSUE TITLE
h264encode error

### ISSUE THREAD

**Issue by ccxiaop** [intel/libva-utils#160]
when running h264encode ,but error happens.
as log:
root@ubuntu:~/yuv_src# h264encode  -w 176 -h 144  --fourcc NV12 --profile BP
Source YUV file suzie_qcif_nv12.yuv with 1 frames

INPUT:Try to encode H264...
INPUT: Resolution   : 176x144, 60 frames
INPUT: FrameRate    : 30
INPUT: Bitrate      : 182476
INPUT: Slieces      : 1
INPUT: IntraPeriod  : 30
INPUT: IDRPeriod    : 60
INPUT: IpPeriod     : 1
INPUT: Initial QP   : 26
INPUT: Min QP       : 0
INPUT: Source YUV   : FILE:suzie_qcif_nv12.yuv (fourcc NV12)
INPUT: Coded Clip   : /tmp/test.264
INPUT: Rec   Clip   : Not save reconstructed frame

libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'radeonsi'
libva info: Trying to open /usr/lib/aarch64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
Use profile VAProfileH264ConstrainedBaseline
Support rate control mode (0x16):CBR VBR CQP
RateControl mode: VBR
Support VAConfigAttribEncPackedHeaders
Support 1 RefPicList0 and 0 RefPicList1
0x0xaaab00da3e10 0x2
upload_surface_yuv:vaDeriveImage (328) failed,exit

can anyone help me?

**Comment by XinfengZhang** [comment]
@uartie do you know who are familiar with AMD driver? it should not be a application issue.

**Comment by uartie** [comment]
I do not know who maintains AMD driver.  But seems the issue should be reported to them (whomever they are).

**Comment by uartie** [comment]
@ccxiaop I'm not aware of any active AMD driver developers here in the libva-utils project.  You would likely get better support if you filed this issue with the AMD driver project.
