### ISSUE TITLE
More Decoder Example

### ISSUE THREAD

**Issue by zhoub** [intel/libva-utils#162]
Hi !

It would be great to have also the VP8 decoder, H264 decoder and HEVC decoder.

Thanks in advance.

**Comment by XinfengZhang** [comment]
hi , @zhoub , current decode example does not include bitstream parser --- header parser.  so current decode example always just decode several frames, and the bitstream is a array in the code. my concern is: if we add header parser, seems we are program a common tool, which maybe is duplicated with ffmpeg-vaapi, gstreamer-vaapi.

**Comment by zhoub** [comment]
Hi

Understood, the ffmpeg-vaapi seems okay.

Thanks. Close this issue.
