### ISSUE TITLE
Consider adding a "--repeat" option to the encode/ binaries

### ISSUE THREAD

**Issue by yellowdoge** [intel/libva-utils#209]
The binaries generated under the decode/ folder (e.g.` vp8enc`) have a few command line options.

It'd be great to add a `--repeat <num_repeat times>` option to the [existing ones](https://github.com/intel/libva-utils/blob/master/encode/vp8enc.c#L982) to allow for the input YUV file to be encoded several times (but with the initialization and destruction of shared data structures shared.  This will allow for longer encoding sessions without having to provide large input files (YUV files in particular can get very large quickly).

I have a quick concept for vp8enc that I can PR for if interesting.

**Comment by sreerenjb** [comment]
It seems to be a good feature to me. +1

**Comment by sreerenjb** [comment]
@xuguangxin @xhaihao @XinfengZhang
