### ISSUE TITLE
image dislocation occurred when creating RGBA Format vaCreateSurfaceusing GBM fd

### ISSUE THREAD

**Issue by fangdichan** [intel/libva-utils#242]
The image format is RGBA, which is stored in the GPU. The size is width=720,height=1280,stride=3072, and it needs to be compressed into H264. In order to reduce memory copy, use GBM DMAbuf's fd to create RGBA Format vaCreateSurface, but the resulting graph is confused.

After testing, it was found that the surface was created successfully, but there were problems with the graphics in the surface. Using vaSyncSurface  vaDeriveImage vaMapBuffer to read out the data from the surface, the RGBA graphics in the surface were exported, and the following rules were found:

One line of graph is truncated into a 6x128pix(128*4=512 bytes) long paragraph, and then eight lines of 128pix data are taken at a time and unrolled.

![image](https://user-images.githubusercontent.com/43296986/125439819-eaa5f11c-7aa7-4b01-87a0-619b70b2e38a.png)

    va_attrib_extbuf.pixel_format = VA_FOURCC_RGBA; 
    va_attrib_extbuf.width = w; 
    va_attrib_extbuf.height = h; 
    va_attrib_extbuf.data_size = s * h; 
    va_attrib_extbuf.num_planes = 1; 
    va_attrib_extbuf.pitches[0] = s; 
    va_attrib_extbuf.offsets[0] = 0; 
    va_attrib_extbuf.buffers = (unsigned long*)&(fd); 
    va_attrib_extbuf.num_buffers = 1; 
    va_attrib_extbuf.flags = 0; 
    va_attrib_extbuf.private_data = 0; 

    va_attribs[0].type = VASurfaceAttribMemoryType; 
    va_attribs[0].flags = VA_SURFACE_ATTRIB_SETTABLE; 
    va_attribs[0].value.type = VAGenericValueTypeInteger; 
    va_attribs[0].value.value.i = VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME; 

    va_attribs[1].type = VASurfaceAttribExternalBufferDescriptor; 
    va_attribs[1].flags = VA_SURFACE_ATTRIB_SETTABLE; 
    va_attribs[1].value.type = VAGenericValueTypePointer; 
    va_attribs[1].value.value.p = &va_attrib_extbuf; 
ret = vaCreateSurfaces(va_dpy, VA_RT_FORMAT_RGB32, w,h, &vaSurfaceID, 1, va_attribs, 2);

**Comment by XinfengZhang** [comment]
one question about the layout of the BGRA surface, it is tiling or linear?

**Comment by fangdichan** [comment]
> , it is tiling or linear?



> one question about the layout of the BGRA surface, it is tiling or linear?



> one question about the layout of the BGRA surface, it is tiling or linear?

I’m not sure the layout in gpu memory, I try map to cpu memory, then map to the surface, it works, but it need 25ms, that’s too slow and cpu load up

**Comment by XinfengZhang** [comment]
you could use vaGetImage to read the surface after vaCreateSurfaces, but I suppose the result is same as vaDeriveImage+ vaMapBuffer,  I suspect it is because the layout of the surfaces.
your call sequence should be:
create a surface in other component (3d, OCL ...) (tile or linear?), then call vaCreateSurfaces with the fd (tile or linear ? have you set VA_SURFACE_EXTBUF_DESC_ENABLE_TILING?), then read the surface.
how about the platform and driver name? it is i965 or iHD?

**Comment by fangdichan** [comment]
> you could use vaGetImage to read the surface after vaCreateSurfaces, but I suppose the result is same as vaDeriveImage+ vaMapBuffer, I suspect it is because the layout of the surfaces.
> your call sequence should be:
> create a surface in other component (3d, OCL ...) (tile or linear?), then call vaCreateSurfaces with the fd (tile or linear ? have you set VA_SURFACE_EXTBUF_DESC_ENABLE_TILING?), then read the surface.
> how about the platform and driver name? it is i965 or iHD?

the platform is i915, Just like you said, the layout is tile, size is 4KB, Consistent with my phenomenon. 

defined in drm_fourcc.h:
/*
 * Intel Y-tiling layout
 *
 * This is a tiled layout using 4Kb tiles (except on gen2 where the tiles 2Kb)
 * in row-major layout. Within the tile bytes are laid out in OWORD (16 bytes)
 * chunks column-major, with a platform-dependent height. On top of that the
 * memory can apply platform-depending swizzling of some higher address bits
 * into bit6.
 *
 * This format is highly platforms specific and not useful for cross-driver
 * sharing. It exists since on a given platform it does uniquely identify the
 * layout in a simple way for i915-specific userspace.
 */
#define I915_FORMAT_MOD_Y_TILED	fourcc_mod_code(INTEL, 2)

but how can i pass the parameters to vaCreateSurfaces?

va_attrib_extbuf.pixel_format = VA_FOURCC_RGBA; 
va_attrib_extbuf.width = w; 
va_attrib_extbuf.height = h; 
va_attrib_extbuf.data_size = s * h; 
va_attrib_extbuf.num_planes = 1; 
va_attrib_extbuf.pitches[0] = s; 
va_attrib_extbuf.offsets[0] = 0; 
va_attrib_extbuf.buffers = (unsigned long*)&(fd); 
va_attrib_extbuf.num_buffers = 1; 
va_attrib_extbuf.flags = __VA_SURFACE_EXTBUF_DESC_ENABLE_TILING_;                The problem is still_
va_attrib_extbuf.private_data = 0; 

va_attribs[0].type = VASurfaceAttribMemoryType; 
va_attribs[0].flags = VA_SURFACE_ATTRIB_SETTABLE; 
va_attribs[0].value.type = VAGenericValueTypeInteger; 
va_attribs[0].value.value.i = _VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME;                   maybe VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2?      no image, all black_

va_attribs[1].type = VASurfaceAttribExternalBufferDescriptor; 
va_attribs[1].flags = VA_SURFACE_ATTRIB_SETTABLE; 
va_attribs[1].value.type = VAGenericValueTypePointer; 
va_attribs[1].value.value.p = &va_attrib_extbuf; 

ret = vaCreateSurfaces(va_dpy, VA_RT_FORMAT_RGB32, w,h, &vaSurfaceID, 1, va_attribs, 2);

**Comment by fangdichan** [comment]
> you could use vaGetImage to read the surface after vaCreateSurfaces, but I suppose the result is same as vaDeriveImage+ vaMapBuffer, I suspect it is because the layout of the surfaces.
> your call sequence should be:
> create a surface in other component (3d, OCL ...) (tile or linear?), then call vaCreateSurfaces with the fd (tile or linear ? have you set VA_SURFACE_EXTBUF_DESC_ENABLE_TILING?), then read the surface.
> how about the platform and driver name? it is i965 or iHD?

thanks a lot, It's done.

va_attribs[1].value.value.p = &va_attrib_extbuf;

should use VADRMPRIMESurfaceDescriptor, not VASurfaceAttribExternalBuffers. and set the parameters:

    surface_desc.fourcc = VA_FOURCC_RGBA;
    surface_desc.width = w;
    surface_desc.height = h;
    surface_desc.num_objects = 1;
    surface_desc.objects[0].fd = fd;
    surface_desc.objects[0].size = s*h;
    surface_desc.objects[0].drm_format_modifier = I915_FORMAT_MOD_X_TILED;
    surface_desc.num_layers = 1;
    surface_desc.layers[0].drm_format = DRM_FORMAT_RGBA8888;
    surface_desc.layers[0].num_planes = 1;
    surface_desc.layers[0].object_index[0] = 0;
    surface_desc.layers[0].offset[0] = 0;
    surface_desc.layers[0].pitch[0] = s;
