### ISSUE TITLE
Runtime Error on sample_decode/encode

### ISSUE THREAD

**Issue by qin53027** [intel/libva-utils#249]
Hi,

Yesterday I have install the Intel Media SDK:  https://github.com/Intel-Media-SDK/MediaSDK. Also I have installed the libva

Both installation has been successful

But when I run: vainfo, I have following error

libva info: VA-API version 1.13.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
vaInitialize failed with error code 1 (operation failed),exit

Also when I run the decode example, I also get error (also similar error on the encode run):

./sample_decode h264 -i ./home/jiande/Pictures/sample_720p.h264 -o output.yuv -sw

[ERROR], sts=MFX_ERR_NULL_PTR(-2), Init, m_fSource pointer is NULL at /home/jiande/intel_msdk/build/MediaSDK/samples/sample_common/src/sample_utils.cpp:706
[ERROR], sts=MFX_ERR_NULL_PTR(-2), Init, m_FileReader->Init failed at /home/jiande/intel_msdk/build/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:382
[ERROR], sts=MFX_ERR_NULL_PTR(-2), main, Pipeline.Init failed at /home/jiande/intel_msdk/build/MediaSDK/samples/sample_decode/src/sample_decode.cpp:807

I guess that the installation of the libva may not be correct or something else.  could you please give me the suggestions how to fix the problem?

My system is ubuntu 20.04 has the Nvia GPU only

Thanks a lot
Jimmy

**Comment by jeffshuai** [comment]
set the LIB_VA_NAME=vdpau    in your    Nvia?? GPU

**Comment by XinfengZhang** [comment]
@qin53027  MediaSDK and iHD just support intel gpu.
