### ISSUE TITLE
vainfo stopped working when updating Mesa from 21.1.8 to 21.2.x or anything higher

### ISSUE THREAD

**Issue by wblaszcz** [intel/libva-utils#256]
Tried up to Mesa 21.3.6. I get the following error:

libva info: VA-API version 1.13.0
libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
vaInitialize failed with error code 3 (invalid VADisplay),exit

Reverting back to Mesa 21.1.8 resolves the issue.

Not sure if this is a libva-utils issue or a Mesa issue.

Have done a git bisect on Mesa:
9cc4ce16fd1871393c38125b6b4c492f3f4a4725 is the first bad commit

Further info:
When setting LIBVA_DRIVER_NAME=iHD, I get the following:

libva info: VA-API version 1.13.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva error: /usr/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit

**Comment by wblaszcz** [comment]
Raised https://gitlab.freedesktop.org/mesa/mesa/-/issues/6065

**Comment by XinfengZhang** [comment]
please promote the libva to 2.14.0, suppose it is just because the "crocus"  for first issue. 
the second issue is a little complicate, could you share some platform information

**Comment by wblaszcz** [comment]
I'm pretty sure this is a Mesa build issue. See https://gitlab.freedesktop.org/mesa/mesa/-/issues/6065

"Have since found that adding the build parameter -Dprefer-iris=false resolves the issue. (to the Mesa build)" 
My platform is LFS. i.e. It's custom built.

**Comment by wblaszcz** [comment]
This is a Mesa build issue
