### ISSUE TITLE
Failed to create dedicated X11 display !

### ISSUE THREAD

**Issue by pc00per** [intel/libva-utils#276]
`$ vainfo`
```
Failed to create dedicated X11 display!
Segmentation fault (core dumped)
```
GNOME 42 / Wayland / Nvidia Proprietary Drivers
I know it's not Intel GPU. But nvidia supports only NVDEC & vdpau implementations (currently on [vdpau backend for libva](https://github.com/xuanruiqi/vdpau-va-driver-vp9))

**Comment by XinfengZhang** [comment]
could you help to try vainfo --display drm --device /dev/dri/renderD128 , and I am wondering whether Nvidia proprietary driver could support libva...

**Comment by pc00per** [comment]
> could you help to try vainfo --display drm --device /dev/dri/renderD128 , and I am wondering whether Nvidia proprietary driver could support libva...

```
libva error: /usr/lib/dri/nvidia_drv_video.so init failed
vaInitialize failed with error code -1 (unknown libva error),exit
```

**Comment by pc00per** [comment]
Hm. Seems like it's the above arch package issue... Other drivers work fine on wayland.
