### ISSUE TITLE
Retag of 2.18.1

### ISSUE THREAD

**Issue by nanonyme** [intel/libva-utils#326]
Looks like this project changed the meaning of 2.18.1 several days ago. I assume this was an accident and you actually meant to create 2.18.2. Moving of tags in git does not work and anyone who has pulled this repo will now have different view of the repo than this upstream one. Git will not move the tag when pulling. I would suggest with haste creating 2.18.2 so there will be an unambiguous latest tag for downstreams to use.

**Comment by XinfengZhang** [comment]
sorry for one mistake,  I create 2.18.2 [https://github.com/intel/libva-utils/releases/tag/2.18.2] to be the latest one, but it 2.18.1 could not be recovered. sorry about it.

**Comment by nanonyme** [comment]
Sure, no problem. That's why I suggested another version bump in the first place. Thanks for quick fix.
