### ISSUE TITLE
libva-utils test should not check vendor string

### ISSUE THREAD

**Issue by XinfengZhang** [intel/libva-utils#93]
TEST_F(VAAPIQueryVendor, Intel_i965_Vendor), if the vendor is not "Intel i965 driver". it will be failed.

**Comment by uartie** [comment]
Yes, it is a driver specific test.  We may remove them in the future, but for now you can just run the tests like:
```
test_va_api --gtest_filter=-*i965*
```

**Comment by XinfengZhang** [comment]
ok
