### ISSUE TITLE
VAAPIInitTerminate.vaInitialize_vaTerminate_i965_vaSetDriverName" , failed because mismatched driver name

### ISSUE THREAD

**Issue by XinfengZhang** [intel/libva-utils#94]
vaSetDriverName to i965
but actually the driver maybe is iHD or from other vendor

**Comment by uartie** [comment]
Yes, it is a driver specific test.  We may remove them in the future, but for now you can just run the tests like:
```
test_va_api --gtest_filter=-*i965*
```
