### ISSUE TITLE
libva-utils should not call setenv("LIBVA_DRIVER_NAME", "i965", 1), it will force enviorment variable  

### ISSUE THREAD

**Issue by XinfengZhang** [intel/libva-utils#95]
don't work , if the driver name change.

**Comment by uartie** [comment]
Yes, it is a driver specific test.  We may remove them in the future, but for now you can just run the tests like:
```
test_va_api --gtest_filter=-*i965*
```

The test fixture will save/restore LIBVA_DRIVER_NAME environment variable before/after each test case is executed.
